name: Awesome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
  - cron: 0 0 * * *

jobs:
  test:
    name: Test for stale links in README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Test with Awesome Bot
      run: |
        gem install awesome_bot
        awesome_bot README.md --allow-redirect --allow-dupe
